config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'
	root 'welcome#index'

	get '/login' => 'users#new_login'
	post '/login' => 'users#create_login'
	get '/logout' => 'users#logout'

	get '/signup' => 'users#new_user'
	post '/users' => 'users#create_user'

	resources :articles
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: { minimum: 5 }

	def self.create(params, current_user)
		param = {:title => params[:title], :body => params[:body], :user_id => current_user.id}
		article = Article.new(param)
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :articles, dependent: :destroy
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, length: { minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def authorize
		redirect_to '/login', notice: "YOU NEED TO LOGIN FIRST!" unless current_user
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authorize, except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.create(params[:article], current_user)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.user_id == current_user.id
			if @article.update!({:title => params[:article][:title], :body => params[:article][:body]})
				redirect_to @article
			else
				render 'edit'
			end
		else
			redirect_to '/articles', notice: "You are not allowed to edit other user's posts!"
		end
	end

	def destroy
		@article = Article.find(params[:id])
		if @article.user_id == current_user.id
			@article.destroy
			redirect_to articles_path
		else
			redirect_to '/articles', notice: "You are not allowed to delete other user's posts!"
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new_user
		@user = User.new
	end

	def create_user
		@user = User.new(user_params)
		if params[:password] == params[:password_confirmation]
			if @user.save
				session[:user_id] = @user.id
				redirect_to '/articles'
			else
				render 'new_user'
			end
		else
			@user.errors.add(:base, "Password and confirm password do not match")
		end
	end

	def new_login
	end

	def create_login
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to '/articles'
		else
			redirect_to '/login'
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to '/login'
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<%= link_to 'New article', '/articles/new' %>

<p>
	<% flash.each do |name, msg| %>
		<strong><%= content_tag :div, msg, class: name %></strong>
	<% end %>
</p>
<table>
	<tr>
		<th>Title</th>
		<th>Body</th>
		<th></th>
	</tr>
	<% @articles.each do |article| %>
		<tr>
			<td><%= article.title  %></td>
			<td><%= article.body %></td>
			<td><%= link_to 'Show', article_path(article) %></td>
			<td><%= link_to 'Edit', edit_article_path(article) %></td>
			<td><%= link_to 'Destroy', article_path(article), method: :delete, 
			data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<p>
	<%= link_to 'Logout', logout_path %>
</p>

<p>
	Existing User? <%= link_to 'Login', login_path %>
</p>

<p>
	New User? <%= link_to 'Signup', signup_path %>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Body:</strong>
	<%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', '/articles' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new_login.html.erb
<h1>Login</h1>

<p>
  <% flash.each do |name, msg| %>
    <strong><%= content_tag :div, msg, class: name %></strong>
  <% end %>
</p>

<%= form_tag '/login' do %>
  <p>
    Email: <%= text_field_tag :email %>
  </p>
  <p>
    Password: <%= password_field_tag :password %>
  </p>
  <p>
    <%= submit_tag "Submit" %>
  </p>
<% end %>

<p>
	New User? <%= link_to 'Signup', signup_path %>
</p>

<p>
	<%= link_to 'Home', welcome_index_path %>
</p>

app/views/users/new_user.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>
	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Account could not be created</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
	<p>
		Email: <%= f.text_field :email %>
	</p>
	<p>
		Password: <%= f.password_field :password %>
	</p>
	<p>
		Confirm Password: <%= f.password_field :password_confirmation %><br>
	</p>
	<p>
		<%= f.submit "Signup" %>
	</p>
<% end %>

<p>
	Existing User? <%= link_to 'Login', login_path %>
</p>

<p>
	<%= link_to 'Home', welcome_index_path %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome to the WEBLOG</h1>

<p>
	<%= link_to 'My Blog', controller: 'articles' %>
</p>

<p>
	Existing User? <%= link_to 'Login', login_path %>
</p>

<p>
	New User? <%= link_to 'Signup', signup_path %>
</p>